SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO21;
CREATE DATABASE DBEXERCICIO21;
USE DBEXERCICIO21;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    PRIMARY KEY (IDALUNO)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCURSO)
);

CREATE TABLE RECITAL (
	IDRECITAL INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    DT_RECITAL DATE NOT NULL,
    LOCAL_RECITAL VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDRECITAL)
);

CREATE TABLE AULA (
	IDAULA INT NOT NULL AUTO_INCREMENT,
    IDCURSO INT NOT NULL,
    DT_CURSO DATE NOT NULL,
    PRIMARY KEY (IDAULA),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO)
);

CREATE TABLE PARTICIPACAO (
	IDRECITAL INT NOT NULL,
	IDALUNO INT NOT NULL,
	PRIMARY KEY (IDRECITAL, IDALUNO),
	FOREIGN KEY (IDRECITAL) REFERENCES RECITAL (IDRECITAL),
	FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);

CREATE TABLE MATRICULA (
	IDCURSO INT NOT NULL,
	IDALUNO INT NOT NULL,
	PRIMARY KEY (IDCURSO,IDALUNO),
	FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO),
	FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);

CREATE TABLE FREQUENCIA (
	IDALUNO INT NOT NULL,
    IDAULA INT NOT NULL,
    PRESENTE CHAR(1) NOT NULL,
    PRIMARY KEY (IDALUNO, IDAULA),
    FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO),
    FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA)
);
