-- DESABILITANDO O MODO SEGURO
SET SQL_SAFE_UPDATES=0;

-- APAGANDO O BANCO DE DADOS CASO EXISTE
DROP DATABASE IF EXISTS DBEXERCICIO03;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO03;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO03;

-- CRIANDO AS TABELAS
CREATE TABLE PESQUISA (
	IDPESQUISA INT NOT NULL auto_increment,
	NOME VARCHAR(120) NOT NULL,
    CIDADE VARCHAR(120),
    IDADE INT,
    NOTA DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (IDPESQUISA)
);

-- INSERIR DADOS NA TABELA (1 REGISTRO)
INSERT INTO PESQUISA(NOME,CIDADE,IDADE,NOTA) VALUES('Pedro', 'São Paulo',34,83.0);

-- INCLUINDO VARIOS REGISTROS
INSERT INTO PESQUISA(NOME,CIDADE,IDADE,NOTA) VALUES
	('Maria','São Paulo',29,59.0),
	('Janaina','Rio de Janeiro',32,86.0),
    ('Wong','Brasília',43,89.0),
    ('Roberto','Salvador',38,98.0),
    ('Marco','Curitiba',31,61.0),
    ('Paula','Belo Horizonte',34,44.0);

-- SELECIONAR DADOS NA TABELA E ME MOSTRAR
SELECT * FROM PESQUISA WHERE NOME = 'ROBERTO';
-- WHERE É FILTRO JUNTO DO SELECT

-- MUDAR DADOS COM O UPDATE
UPDATE PESQUISA SET IDADE = 28 WHERE IDPESQUISA = 5;
UPDATE PESQUISA SET NOTA = 69.2, CIDADE = 'Florianópolis' WHERE NOME='MARIA';

-- APAGAR LINHAS

DELETE FROM PESQUISA WHERE IDADE > 40;
