SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO22;
CREATE DATABASE DBEXERCICIO22;
USE DBEXERCICIO22;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT,
    IDCLIENTE INT NOT NULL,
    PRIMARY KEY (IDCOMPRA),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE AUTOR (
	IDAUTOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120),
    PRIMARY KEY (IDAUTOR)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT,
    IDAUTOR INT NOT NULL,
    IDCOMPRA INT NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDLIVRO),
    FOREIGN KEY (IDAUTOR) REFERENCES AUTOR (IDAUTOR),
    FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
);

CREATE TABLE RESERVA (
	IDCLIENTE INT NOT NULL,
    IDLIVRO INT NOT NULL,
    PRIMARY KEY (IDCLIENTE,IDLIVRO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
    FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
);

    