SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO31;
CREATE DATABASE DBEXERCICIO31;
USE DBEXERCICIO31;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	SEXO ENUM ('M', 'F'),
	IDADE int,
	CIDADE VARCHAR(20)
);


INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ANDERSON', 17, 'M','PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CESAR', 21, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DANIEL', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DIEGO', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GABRIEL', 19, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOAO', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LEONARDO', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCAS', 20, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('PRISCILA', 19, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RENATA', 21, 'F', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARIA', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TANIA', 19, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOSE', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARISA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOANA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ALICE', 21, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('TADEU', 18, 'M', 'TUBARAO');

-- RESPOSTAS EXERCICIOS

-- 1)
SELECT * FROM ALUNO WHERE SEXO ="M";

-- 2)

SELECT * FROM ALUNO WHERE IDADE = 19;

-- 3)

SELECT * FROM ALUNO WHERE NOME LIKE "D%";

-- 4)

SELECT * FROM ALUNO WHERE IDADE BETWEEN 20 AND 22;

-- 5)

SELECT * FROM ALUNO WHERE CIDADE IS NULL;

-- 6)

SELECT * FROM ALUNO WHERE CIDADE = "Blumenau";

-- 7)

SELECT * FROM ALUNO WHERE IDADE <> 18;

-- 8)

SELECT * FROM ALUNO WHERE NOME LIKE "%Ri%";

-- 9)

SELECT * FROM ALUNO WHERE CIDADE = "São José" AND  SEXO ="M" AND IDADE < 20;

-- 10)

SELECT * FROM ALUNO WHERE (SEXO ="F" AND IDADE > 20) OR (SEXO ="M" AND IDADE > 17);

-- 11)

SELECT * FROM ALUNO WHERE NOME LIKE "%A%" AND NOME LIKE "%R%";

-- 12)

SELECT NOME,IDADE FROM ALUNO WHERE SEXO = "F";

-- 13)

SELECT CODIGO,NOME FROM ALUNO WHERE CIDADE = "Blumenal";

-- 14)

SELECT NOME,CIDADE FROM ALUNO WHERE IDADE < 18;

-- 15)

SELECT NOME,CIDADE FROM ALUNO WHERE IDADE BETWEEN 15 AND 18 AND CIDADE <> "Palhoça";

-- 16)

SELECT CIDADE FROM ALUNO WHERE CIDADE  IS NOT NULL;

-- 17)

SELECT IDALUNO,NOME  FROM ALUNO ORDER BY NOME DESC;

-- 18)

SELECT * FROM ALUNO ORDER BY IDADE DESC, NOME ASC;

-- 19)

SELECT * FROM ALUNO ORDER BY SEXO,NOME;

-- 20)

UPDATE ALUNO SET IDADE = 20 WHERE NOME = "Jose";

-- 21)

UPDATE ALUNO SET IDADE = 21 WHERE NOME IN("Tadeu","Cesar","Marisa");

-- 22)

UPDATE ALUNO SET CIDADE = NULL WHERE IDADE > 24;

-- 23) 

DELETE FROM ALUNO WHERE CIDADE IS NULL;

-- 24)

DELETE FROM ALUNO WHERE CIDADE = "Tubarão" AND  IDADE > 15 AND SEXO ="M";

-- 25)

DELETE FROM ALUNO WHERE NOME IN("Tadeu","Alice","Maria") AND IDADE = 19;

-- 26)

DELETE FROM ALUNO WHERE (IDADE < 18 AND SEXO = "M") OR (IDADE < 21 AND SEXO = "F");