SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO12;
CREATE DATABASE DBEXERCICIO12;
USE DBEXERCICIO12;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CIDADE VARCHAR(120),
    PRIMARY KEY (IDALUNO)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT,
    DT_MATRICULA DATE NOT NULL,
    CURSO VARCHAR(120) NOT NULL,
    IDALUNO INT NOT NULL,
    PRIMARY KEY (IDMATRICULA),
    FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
);

