SET SQL_SAFE_UPDATES=0;
DROP DATABASE IF EXISTS DBEXERCICIO07;
CREATE DATABASE DBEXERCICIO07;
USE DBEXERCICIO07;

CREATE TABLE CARRO (

IDCARRO INT NOT NULL AUTO_INCREMENT,
MARCA VARCHAR(45) NOT NULL,
MODELO VARCHAR(45) NOT NULL,
ANO_DE_FABRICACAO INT,
ANO_DO_MODELO INT,
PLACA VARCHAR(7) NOT NULL,
COR VARCHAR(45) NOT NULL,
PRIMARY KEY (IDCARRO)

);

INSERT INTO CARRO (MARCA,MODELO,ANO_DE_FABRICACAO,ANO_DO_MODELO,PLACA,COR) VALUES
	('Toyota','Corolla XEi 2.0',2021,2022,'RZA4J82','Prata'),
    ('Volkswagen','T-Cross Comfortline 200 TSI',2020,2021,'QWE7H19','Branco'),
    ('Chevrolet','Onix LT 1.0 Turbo',2022,2023,'BGT9C57','Azul metálico'),
    ('Honda','Civic Touring 1.5 Turbo',2019,2020,'LKM3F24','Cinza grafite');
    
    SELECT * FROM CARRO;
    
    UPDATE CARRO SET COR='Vermelho' WHERE COR='Cinza grafite';
	UPDATE CARRO SET COR='Azul' WHERE COR='Prata';
    
    DELETE FROM CARRO WHERE PLACA='QWE7H19';

    
    