SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCIO25;
CREATE DATABASE DBEXERCIO25;
USE DBEXERCIO25;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL,
    TURMA VARCHAR(50) NOT NULL
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL,
    AUTOR VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDLIVRO)
);

CREATE TABLE EMPRESTIMO (
	IDEMPRESTIMO INT NOT NULL,
    IDALUNO INT NOT NULL,
    IDLIVRO INT NOT NULL,
    FOREIGN KEY (IDLIVRO) REFERENCES LIVRO(IDLIVRO)
);

-- CORREÇÃO DO EXERCICIO

ALTER TABLE ALUNO
	ADD COLUMN NOME VARCHAR(120) NOT NULL,
	ADD PRIMARY KEY (IDALUNO);

ALTER TABLE LIVRO
	ADD COLUMN TITULO VARCHAR(120) NOT NULL;

ALTER TABLE EMPRESTIMO
	ADD COLUMN DT_EMPRESTIMO DATE NOT NULL,
	ADD COLUMN DT_DEVOLUCAO DATE NOT NULL,
	ADD PRIMARY KEY (IDEMPRESTIMO),
	ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO);
