SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO11;
CREATE DATABASE DBEXERCICIO11;
USE DBEXERCICIO11;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
	PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE PREFERENCIA (
	IDCLIENTE INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    PRIMARY KEY (IDCLIENTE, IDPRODUTO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);