SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO10;
CREATE DATABASE DBEXERCICIO10;
USE DBEXERCICIO10;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT,
    DT_PEDIDO DATE NOT NULL,
    PRODUTO VARCHAR(120) NOT NULL,
    QTDE INT NOT NULL,
    IDCLIENTE INT NOT NULL,
    PRIMARY KEY (IDPEDIDO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);