SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO23;
CREATE DATABASE DBEXERCICIO23;
USE DBEXERCICIO23;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDERECO VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE ENTREGADOR (
	IDENTREGADOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDENTREGADOR)
);

CREATE TABLE RESTAURANTE (
	IDRESTAURANTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    ENDERECO VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDRESTAURANTE)
);

CREATE TABLE PRATO (
	IDPRATO INT NOT NULL AUTO_INCREMENT,
    IDRESTAURANTE INT NOT NULL,
    NOME VARCHAR(120),
    PRIMARY KEY (IDPRATO),
    FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE (IDRESTAURANTE)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT,
    IDCLIENTE INT NOT NULL,
    IDENTREGADOR INT NOT NULL,
    DT_ENTREGA DATE NOT NULL,
    PRIMARY KEY (IDPEDIDO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
    FOREIGN KEY (IDENTREGADOR) REFERENCES ENTREGADOR (IDENTREGADOR)
);

CREATE TABLE ITEM_PEDIDO (
	IDPEDIDO INT NOT NULL,
    IDPRATO INT NOT NULL,
    QUANTIDADE CHAR(2) NOT NULL,
    VALOR DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (IDPEDIDO, IDPRATO),
    FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (IDPEDIDO),
    FOREIGN KEY (IDPRATO) REFERENCES PRATO (IDPRATO)
);