SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIOFINAL;
CREATE DATABASE DBEXERCICIOFINAL;
USE DBEXERCICIOFINAL;

-- Exercício 01 

CREATE TABLE USUARIO (
    IDUSUARIO INT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100)
);

CREATE TABLE EPISODIO (
    IDEPISODIO INT PRIMARY KEY,
    TITULO VARCHAR(100),
    NUMERO INT,
    TEMPORADA INT,
    DURACAO TIME
);

CREATE TABLE ACESSO (
    IDACESSO INT PRIMARY KEY,
    IDUSUARIO INT,
    IDEPISODIO INT,
    DH_ACESSO DATETIME,
    TEMPO_ASSISTIDO TIME,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    FOREIGN KEY (IDEPISODIO) REFERENCES EPISODIO(IDEPISODIO)
);

-- Exercício 02

ALTER TABLE USUARIO
ADD COLUMN DT_REGISTRO DATETIME;

ALTER TABLE EPISODIO
ADD COLUMN DT_PUBLICACAO DATETIME;

-- Exercício 03

INSERT INTO USUARIO (IDUSUARIO, NOME, EMAIL, DT_REGISTRO)
VALUES (1, 'João da Silva', 'joao.silva@superemail.com.br', NOW());

-- Exercício 04

UPDATE EPISODIO
SET DURACAO = '00:42:55'
WHERE NUMERO = 3 AND TEMPORADA = 5;

-- Exercício 05

DELETE FROM EPISODIO
WHERE NUMERO = 25 AND TEMPORADA = 2;

-- exercício 06

SELECT
    U.IDUSUARIO,
    U.NOME,
    E.NUMERO AS NUMERO_EPISODIO,
    E.TEMPORADA AS TEMPORADA_EPISODIO,
    A.IDACESSO,
    A.DH_ACESSO
FROM
    ACESSO AS A
JOIN
    USUARIO AS U ON A.IDUSUARIO = U.IDUSUARIO
JOIN
    EPISODIO AS E ON A.IDEPISODIO = E.IDEPISODIO
WHERE
    A.DH_ACESSO BETWEEN '2025-05-01 00:00:00' AND '2025-05-31 23:59:59';

