SET SQL_SAFE_UPDATES=0;
DROP DATABASE IF EXISTS DBEXERCICIO05;
CREATE DATABASE DBEXERCICIO05;
USE DBEXERCICIO05;

CREATE TABLE COLETA (
	IDCOLETA INT NOT NULL AUTO_INCREMENT,
    BALNEARIO VARCHAR(120) NOT NULL,
    PONTO INT NOT NULL,
    REFERENCIA VARCHAR(120),
    DATA_DA_COLETA DATE NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDCOLETA)
    
	);
    
    INSERT INTO COLETA (BALNEARIO,PONTO,REFERENCIA,DATA_DA_COLETA,SITUACAO) VALUES
		('PRAIA DA BARRA DA LAGOA',32, 'APROXIMADAMENTE 50 METROS À ESQ. DOS MOLHES', '2024-01-30', 'PRÓPRIA'),
        ('PRAIA DA BARRA DA LAGOA',88,'Fte Rua Aconchego do Mar', '2024-01-30','PRÓPRIA'),
        ('PRAIA DA BASE AÉREA',49,'AO LADO DO TRAPICHE','2024-01-29','PRÓPRIA'),
        ('PRAIA DA BEIRA MAR NORTE',11,'EM FRENTE AO MONUMENTO DA PILÍCIA MILITAR','2024-01-29','IMPRÓPRIA');
        
	 UPDATE COLETA SET SITUACAO='PRÓPRIA' WHERE SITUACAO='IMPRÓPRIA';
     UPDATE COLETA SET DATA_DA_COLETA = '2025-04-01' 

SELECT * FROM COLETA
