-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO27;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO27;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO27;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE INSTRUTOR (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE PROFESSOR (
	IDPROFESSOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT
    , IDINSTRUTOR INT NOT NULL
    , PROFESSOR INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , DT_FINAL DATE NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
	DT_MATRICULA DATE NOT NULL
);

CREATE TABLE MATERIAL (
	IDMATERIAL INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , LINK_MATERIAL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDMATERIAL)
);

CREATE TABLE ASSISTIR (
	IDASSISTIR INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDASSISTIR)
);


CREATE TABLE COMENTARIO (
	IDCOMENTARIO INT NOT NULL AUTO_INCREMENT
    , IDAULA INT NOT NULL
    , DT_CONENTARIO DATE NOT NULL
    , IDALUNO INT NOT NULL
    , TEXTO_COMENTARIO VARCHAR(200) NOT NULL
    , IDPROFESSOR INT
    , IDINSTRUTOR INT
    , TEXTO_RESPOSTA VARCHAR(200)
    , PRIMARY KEY (IDCOMENTARIO)
);

-- CORRIGINDO OS ERROS
CREATE TABLE AULA (
	IDAULA INT NOT NULL AUTO_INCREMENT,
	IDCURSO INT NOT NULL,
    DT_AULA DATE NOT NULL,
    PRIMARY KEY (IDAULA),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO)
    );

ALTER TABLE ALUNO
	ADD COLUMN IDALUNO INT NOT NULL,
    ADD PRIMARY KEY (IDALUNO);
    
ALTER TABLE INSTRUTOR
	ADD COLUMN IDINSTRUTOR INT NOT NULL,
    ADD PRIMARY KEY (IDINSTRUTOR);
    
DROP TABLE PROFESSOR;

ALTER TABLE CURSO
	DROP COLUMN PROFESSOR,
    ADD COLUMN DT_INICIO DATE NOT NULL,
    ADD FOREIGN KEY (IDINSTRUTOR) REFERENCES INSTRUTOR (IDINSTRUTOR);
    
ALTER TABLE MATRICULA
	ADD COLUMN IDMATRICULA INT NOT NULL,
    ADD COLUMN IDCURSO INT NOT NULL,
    ADD COLUMN IDALUNO INT NOT NULL,
    ADD PRIMARY KEY (IDMATRICULA),
    ADD FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO),
    ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO);
    
    ALTER TABLE MATERIAL
		ADD COLUMN IDAULA INT NOT NULL,
        ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA);
        
	ALTER TABLE ASSISTIR
		ADD COLUMN IDAULA INT NOT NULL,
        ADD COLUMN DT_ACESSO DATE NOT NULL,
        ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA),
        ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO);
        
	ALTER TABLE COMENTARIO
		DROP COLUMN IDPROFESSOR,
		ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA),
        ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO),
        ADD FOREIGN KEY (IDINSTRUTOR) REFERENCES INSTRUTOR (IDINSTRUTOR);
        

	
