SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO09;
CREATE DATABASE DBEXERCICIO09;
USE DBEXERCICIO09;

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    PRIMARY KEY (IDPESSOA)
);

CREATE TABLE CIN (
	IDCIN INT NOT NULL AUTO_INCREMENT,
    CPF CHAR(11) NOT NULL,
    DT_EMISSAO DATE NOT NULL,
    IDPESSOA INT NOT NULL UNIQUE,
    PRIMARY KEY (IDCIN),
    FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
);


