DROP DATABASE IF EXISTS DBEXERCICIO19;
CREATE DATABASE DBEXERCICIO19;
USE DBEXERCICIO19;

CREATE TABLE CRIMINOSO (
	IDCRIMINOSO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    PRIMARY KEY (IDCRIMINOSO)
);

CREATE TABLE VITIMA (
	IDVITIMA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    DT_NASCMENTO DATE NOT NULL,
    PRIMARY KEY (IDVITIMA)
);

CREATE TABLE CRIME (
	IDCRIME INT NOT NULL AUTO_INCREMENT,
    DT_CRIME DATE NOT NULL,
    DESCRICAO VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDCRIME)
);

CREATE TABLE ARMA (
	IDARMA INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(120) NOT NULL,
    REGISTRO INT,
    CATEGORIA VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDARMA)
);

CREATE TABLE ATACAR (
	IDCRIMINOSO INT NOT NULL,
    IDVITIMA INT NOT NULL,
    PRIMARY KEY (IDCRIMINOSO, IDVITIMA),
    FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO),
    FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA)
);

CREATE TABLE COMETER (
	IDCRIMINOSO INT NOT NULL,
    IDCRIME INT NOT NULL,
    PRIMARY KEY (IDCRIMINOSO, IDCRIME),
    FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO),
    FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);

CREATE TABLE SOFRER (
	IDVITIMA INT NOT NULL,
    IDCRIME INT NOT NULL,
    PRIMARY KEY (IDVITIMA, IDCRIME),
    FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA),
    FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);

CREATE TABLE USAR (
	IDARMA INT NOT NULL,
    IDCRIME INT NOT NULL,
    PRIMARY KEY (IDARMA, IDCRIME),
    FOREIGN KEY (IDARMA) REFERENCES ARMA(IDARMA),
    FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);
