DROP DATABASE IF EXISTS DBEXERCICIO26;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO26;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO26;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , PRIMARY KEY (IDVENDA)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , IDVENDA INT 
    , TITULO VARCHAR(120) NOT NULL
    , AUTOR VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDLIVRO)
    , FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);

CREATE TABLE ALUGUEL (
	IDALUGUEL INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDLIVRO INT NOT NULL
    , DTRESERVA DATE
    , PRIMARY KEY (IDALUGUEL)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
);

-- CORRIGINDO AS TABELAS

ALTER TABLE CLIENTE
	ADD COLUMN NOME VARCHAR(120) NOT NULL;
    
ALTER TABLE VENDA
	ADD COLUMN DTVENDA VARCHAR(45) NOT NULL,
    ADD COLUMN IDCLIENTE INT NOT NULL,
    ADD FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE);

-- AJUSTANDO O NOME DA CHAVE PRIMARIA

ALTER TABLE ALUGUEL
	CHANGE COLUMN IDALUGUEL IDRESERVA INT NOT NULL,
    CHANGE COLUMN DTRESERVA DTRESERVA DATE NOT NULL;
    
RENAME TABLE ALUGUEL TO RESERVA;
