SET SQL_SAFE_UPDATES=0;
DROP DATABASE IF EXISTS DBEXERCICIO08;
CREATE DATABASE DBEXERCICIO08;
USE DBEXERCICIO08;

CREATE TABLE LIVRO (

IDLIVRO INT NOT NULL AUTO_INCREMENT,
TITULO VARCHAR(500) NOT NULL,
AUTOR VARCHAR(500) NOT NULL,
EDITORA VARCHAR (500) NOT NULL,
ANO_PUBLICACAO INT NOT NULL,
PRIMARY KEY (IDLIVRO)

);

INSERT INTO LIVRO (TITULO,AUTOR,EDITORA,ANO_PUBLICACAO) VALUES
	('Os dois morrem no final','Adam Silvera','Rocco',2017),
	('O primeiro a morrer no final','Adam Silvera','Rocco',2022),
	('Aristteles e Dante descobrem os segredos do universo','Benjamin Alire Sáenz','Seguinte',2012),
	('O diário de Anne Frank','Anne Frank','Contact Publishing',1947);

SELECT * FROM LIVRO;

UPDATE LIVRO SET EDITORA='Intrínsseca' WHERE EDITORA='Rocco';
DELETE FROM LIVRO WHERE ANO_PUBLICACAO=2022;


