SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO15;
CREATE DATABASE DBEXERCICIO15;
USE DBEXERCICIO15;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDALUNO)
    );
    
    CREATE TABLE CURSO (
		IDCURSO INT NOT NULL AUTO_INCREMENT,
        TITULO VARCHAR(120) NOT NULL,
        CARGA_HORARIA INT NOT NULL,
        PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
IDMATRICULA INT NOT NULL AUTO_INCREMENT,
DATA_MATRICULA DATE NOT NULL,
IDALUNO INT NOT NULL,
IDCURSO INT NOT NULL,
PRIMARY KEY(IDMATRICULA),
FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO),
FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO)
);

INSERT INTO ALUNO (NOME,EMAIL) VALUES
	('Lucas Mendes','Lucas@email.com'),
	('Júlia Martins','Júlia@email.com'),
	('Pedro Souza','Pedro@email.com');

INSERT INTO CURSO (TITULO,CARGA_HORARIA) VALUES
	('Introdução a python',40),
	('Banco de dados relacional',60),
	('Estatística para dados',50);

INSERT INTO MATRICULA (IDALUNO,IDCURSO,DATA_MATRICULA) VALUES
	(1,1,'2025-03-01'),
    (2,1,'2025-05-03'),
    (1,2,'2025-03-10'),
    (3,3,'2025-04-01'),
    (2,3,'2025-04-02');
    
    SELECT * FROM MATRICULA;
    
-- QUESTÃO 5
SELECT NOME FROM ALUNO;

-- QUESTÃO 6
SELECT TITULO FROM CURSO;

-- QUESTÃO 7
SELECT 
	ALUNO.NOME, 
    ALUNO.EMAIL,
    CURSO.TITULO
FROM 
	ALUNO 
    INNER JOIN MATRICULA ON 
    ALUNO.IDALUNO = MATRICULA.IDALUNO 
    INNER JOIN CURSO ON 
    CURSO.IDCURSO = MATRICULA.IDCURSO
    
WHERE ALUNO.NOME = 'Lucas Mendes';

-- QUESTÃO 8 
SELECT
	MATRICULA.IDMATRICULA,
    MATRICULA.DATA_MATRICULA,
    ALUNO.IDALUNO,
    ALUNO.NOME,
    ALUNO.EMAIL,
    CURSO.IDCURSO,
    CURSO.TITULO,
    CURSO.CARGA_HORARIA
FROM
	ALUNO 
	INNER JOIN MATRICULA ON
	ALUNO.IDALUNO = MATRICULA.IDALUNO
	INNER JOIN CURSO ON
	CURSO.IDCURSO = MATRICULA.IDCURSO;

-- QUESTÃO 9
SELECT
	ALUNO.NOME,
	ALUNO.EMAIL
FROM
 ALUNO
 INNER JOIN MATRICULA ON
 ALUNO.IDALUNO = MATRICULA.IDALUNO
 WHERE MATRICULA.IDCURSO='2';