SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO13;
CREATE DATABASE DBEXERCICIO13;
USE DBEXERCICIO13;


CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120),
    PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE MUSICA (
	IDMUSICA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    CANTOR VARCHAR(120) NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    PRIMARY KEY (IDMUSICA)
);

CREATE TABLE PLAYLIST (
	IDUSUARIO INT NOT NULL,
    IDMUSICA INT NOT NULL,
    PRIMARY KEY (IDUSUARIO, IDMUSICA),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    FOREIGN KEY (IDMUSICA) REFERENCES MUSICA(IDMUSICA)
);