SET SQL_SAFE_UPDATES=0;
DROP DATABASE IF EXISTS DBEXERCICIO06;
CREATE DATABASE DBEXERCICIO06;
USE DBEXERCICIO06;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
    ALUNO VARCHAR(120) NOT NULL,
    PRIMARY KEY(IDALUNO)

); 

INSERT INTO ALUNO (ALUNO) VALUES
	('FULANO'),
    ('CICLANO'),
    ('BELTRANO'),
    ('JOSÉ');
    
    SELECT * FROM ALUNO;
    
    UPDATE ALUNO SET ALUNO='ALUNO01' WHERE ALUNO= 'FULANO';
    UPDATE ALUNO SET ALUNO='ALUNO02' WHERE ALUNO= 'BELTRANO';
    
	DELETE FROM ALUNO WHERE ALUNO = 'CICLANO';