SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO20;
CREATE DATABASE DBEXERCICIO20;
USE DBEXERCICIO20;

CREATE TABLE FILIAL (
	IDFILIAL INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    PRIMARY KEY (IDFILIAL)
    );
    
CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    IDFILIAL INT NOT NULL,
	NOME VARCHAR(120) NOT NULL,
    DTADMISSAO DATE NOT NULL,
    PRIMARY KEY(IDFUNCIONARIO),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
    );
    
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    IDFILIAL INT NOT NULL,
	NOME VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    PRIMARY KEY (IDCLIENTE),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
    );
    
CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL AUTO_INCREMENT,
    IDCLIENTE INT NOT NULL,
    DESCRICAO VARCHAR(120) NOT NULL,
    DTINICIO DATE NOT NULL,
    PRIMARY KEY (IDPROJETO),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    );
    
CREATE TABLE ALOCADO (
	IDFUNCIONARIO INT NOT NULL,
    IDPROJETO INT NOT NULL,
    PRIMARY KEY (IDFUNCIONARIO,IDPROJETO),
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO),
    FOREIGN KEY (IDPROJETO) REFERENCES PROJETO (IDPROJETO)
    );