SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEXERCICIO16;
CREATE DATABASE DBEXERCICIO16;
USE DBEXERCICIO16;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(120) NOT NULL,
    TURMA VARCHAR(45) NOT NULL,
    PRIMARY KEY (IDALUNO)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(120) NOT NULL,
    AUTOR VARCHAR(120) NOT NULL,
    PRIMARY KEY (IDLIVRO)
    );
    
CREATE TABLE EMPRESTIMO (
IDEMPRESTIMO INT NOT NULL AUTO_INCREMENT,
IDALUNO INT NOT NULL,
IDLIVRO INT NOT NULL,
DATA_EMPRESTIMO DATE NOT NULL,
DATA_DEVOLUCAO DATE,
PRIMARY KEY (IDEMPRESTIMO),
FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO),
FOREIGN KEY (IDLIVRO) REFERENCES LIVRO(IDLIVRO)
);

INSERT INTO ALUNO(NOME,TURMA) VALUES 
	('Beatriz Lima','2A'),
	('Rafael Monteiro','1B'),
	('Camila Torres','3C')	;

INSERT INTO LIVRO(TITULO,AUTOR) VALUES
	('Dom Casmurro','Machado de Assis'),
    ('O Pequeno Principe','Antonie de Saint-Exupéry'),
    ('Capitães da Areia','Jorge Amado');
    
INSERT INTO EMPRESTIMO(IDALUNO,IDLIVRO,DATA_EMPRESTIMO,DATA_DEVOLUCAO) VALUES
	(1,1,'2025-04-01','2025-04-10'),
    (2,2,'2025-04-03','2025-04-15'),
    (1,3,'2025-04-05',NULL),
    (3,1,'2025-04-07',NULL);

-- QUESTÃO 10 
SELECT NOME FROM ALUNO;

-- QUESTÃO 11
SELECT TITULO FROM LIVRO;

-- QUESTÃO 12
SELECT
	ALUNO.NOME,
    LIVRO.TITULO,
    EMPRESTIMO.DATA_EMPRESTIMO
FROM 
	ALUNO
    INNER JOIN EMPRESTIMO ON 
    ALUNO.IDALUNO = EMPRESTIMO.IDALUNO
    INNER JOIN LIVRO ON
    LIVRO.IDLIVRO = EMPRESTIMO.IDLIVRO
WHERE
	EMPRESTIMO.DATA_DEVOLUCAO IS NULL;
